configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/openregister%2Fopenregister-b1d4760dff4b14eb6bb962ed8b7b167df2f721ada255d1fd11fa1e96511389bc.yml
openapi_spec_hash: 0fd307a7a9fcef14c870139803c814ad
config_hash: fdea4e3ddcacdadbf8ec360cc2dee658
